V8.1.0 rc
AcademySoftwareFoundation/openvdb pull request #1100
Opened 2021-06-11 22:35 UTC by kmuseth

Release of v8.1.0

2021-06-11 22:59 UTC, apradhana approved these changes

2021-06-12 01:47 UTC, danrbailey requested changes
We shoudn't be merging additional changes from master to v8.1.0_rc now. The release candidate for v8.1.0 is intended to be locked.

2021-06-12 01:47 UTC, danrbailey approved these changes

2021-06-14 09:52 UTC, Idclip approved these changes

2021-06-14 17:19 UTC, danrbailey approved these changes

2021-07-08 03:19 UTC, merged