Adding unsafe methods to the RootNode, InternalNode and LeafNodes
AcademySoftwareFoundation/openvdb pull request #1938
Opened 2024-10-19 00:34 UTC by danrbailey

This adds `isValueOff()` to InternalNode and LeafNode(s) and `probeValue(Index, val)` to LeafNodeBool/LeafNodeMask.

In addition this adds "unsafe" index-based methods to the InternalNode and a few equivalent methods to the LeafNode(s). All these methods have full unit test coverage, below is the complete list of new methods:

**Root Node**

```
RootNode::getValueUnsafe()
RootNode::getChildUnsafe()
RootNode::getConstChildUnsafe()
```

**InternalNode**

```
InternalNode::isValueOff()
InternalNode::getValueUnsafe()
InternalNode::getChildUnsafe()
InternalNode::getConstChildUnsafe()
InternalNode::setActiveStateUnsafe()
InternalNode::setValueOnlyUnsafe()
InternalNode::setValueOnUnsafe()
InternalNode::setValueOffUnsafe()
InternalNode::setChildUnsafe()
InternalNode::resetChildUnsafe()
InternalNode::stealChildUnsafe()
InternalNode::deleteChildUnsafe()
```

**LeafNode (+ LeafNodeMask, LeafNodeBool)**

```
LeafNode::isValueOff()
LeafNode::probeValue(Index,val)
LeafNode::getValueUnsafe()
LeafNode::setActiveStateUnsafe()
LeafNode::setValueOnlyUnsafe()
LeafNode::setValueOnUnsafe()
LeafNode::setValueOffUnsafe()
```

2024-10-23 18:57 UTC, jmertic commented
/easycla

2024-10-26 18:42 UTC, kmuseth requested changes
please see requests for changes

2024-10-26 18:42 UTC, kmuseth commented on openvdb/openvdb/tree/InternalNode.h
> +    // WARNING: For improved performance, these unsafe methods do not check the value or
I would add this comment to each relevant method with `/// @warning`

2024-10-26 18:42 UTC, kmuseth commented on openvdb/openvdb/tree/InternalNode.h
> +    // WARNING: For improved performance, these unsafe methods do not check the value or
oh I see you already did that so never mind

2024-10-26 18:42 UTC, kmuseth commented on openvdb/openvdb/tree/InternalNode.h
> +    if (this->isChildMaskOff(n)) return this->isValueMaskOn(n);
why not shorten these two lines to:

`return this->isChildMaskOff(n) ? this->isValueMaskOn(n) : mNodes[n].getChild()->isValueOff(xyz);`

2024-10-26 18:42 UTC, kmuseth commented on openvdb/openvdb/tree/InternalNode.h
> +InternalNode<ChildT, Log2Dim>::deleteChildUnsafe(Index n, const ValueType& value, bool active)
in the interest of minimizing code duplication and making it more intuitive this method should be implemented in terms of the previous on:

```
template<typename ChildT, Index Log2Dim>
inline void
InternalNode<ChildT, Log2Dim>::deleteChildUnsafe(Index n, const ValueType& value, bool active)
{
   delete this->stealChildUnsafe(n, value, active);
}
```

2024-10-26 18:42 UTC, kmuseth commented on openvdb/openvdb/tree/LeafNode.h
> +    bool isValueOff(Index offset) const { return mValueMask.isOff(offset); }
missing:

`OPENVDB_ASSERT(offset < SIZE);`

2024-10-26 18:42 UTC, kmuseth commented on openvdb/openvdb/tree/RootNode.h
> +    const ValueType& getValueUnsafe(const Coord& xyz) const;
why is this not call `getTileValueUnsafe` ?

2024-10-26 18:42 UTC, kmuseth commented on openvdb/openvdb/tree/RootNode.h
> +    bool getValueUnsafe(const Coord& xyz, ValueType& value) const;
why is this not called `getTileValueUnsafe` ?

2024-10-27 00:15 UTC, danrbailey commented
Addressed all feedback, thanks!

2024-10-29 18:27 UTC, kmuseth approved these changes

2024-10-29 22:18 UTC, merged